### ISSUE TITLE
Inheritance: Final Issues Tracker

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#1312]
- [x] Particle inheriting a missing one fails to load with empty inherit object [@mahagr]
- [x] First time inheritance of section without children, doesn't allow to reorder children [@w00fz]
- [x] Unchecking all the included options of a section, doesn't properly clear the UI of a section, leaving grey background [@w00fz]
- [x] Need a lock info-icon at the beginning of Inheriting from... [@w00fz]
- [x] In side-by-side section view (main | sidebar) the Inheriting from... needs to be just the lock info-icon, no text [@w00fz]
- [x] Load popover needs an option "Inherit every Section and Children" in the Outlines tab [@w00fz]
- [x] When switching to Inheritance always uncheck all Includes before calling the ajax [@w00fz]
- [x] When in No Inheritance, do not allow to change Include status [lock/unlock] [@w00fz]
- [x] Prevent inherited section/particle from selecting nested inheritance [@mahagr]
- [x] Since `Base Outline`introduces back the Layout, we need the Load popover to now also include it in the Outline tab [@mahagr]
- [x] Some Particles in the list field show up as empty when no `layout.yaml` present [@mahagr]
- [x] If Particle gets removed from the layout, properties will not get copied to the inheriting outlines [@mahagr]
- [x] Display list of inherited outlines when editing section/particle [@mahagr]
- [x] Resolve particle id conflicts when inheriting sections and particles from other outlines [@mahagr]
- [x] Allow for a shortcut to easily copy particles/section attributes/children, instead of inheriting first and exiting inheritance later (ref, #50) [@w00fz]
- [x] Atoms implementation for inheritance still missing (ref, #1235, #575)
- [x] Atoms inheritance is missing inherit loop detection

**Comment by mahagr** [comment]
- [ ] Particles should be able to Inherit from the same Outline and only excluding the same instance [@mahagr]

This one cannot be done as the logic for inheriting from the same outline needs very different logic as you may have modified the outline before inheriting. It also needs similar code change throughout, so I decided not to implement it and find out another way to deal with copying sections and particles inside the layout.
