### ISSUE TITLE
Menu rework and enhancements 

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#58]
This is a comprehensive ticket including all the issues reported regarding the menu. Because we are reworking how the menu works and give the many feedbacks received it is easier for us to keep track in one issue only.

- [x] In full width some sublevels aren't expandable [#42]
- [x] Submenus in more than one column does not work [#41, #34]
- [x] Responsive menu might show blank (unstyled) if not in the `navigation` section [#30]
- [x] Support for `Module Positions` and `Particles` (maybe even `Spacer` ?) [Module Picker should support some sort of advanced filtering and probably pagination because the modules list can get big] [#24]
- [x] Configurable Menu overlay from Styles tab [#22]
- [x] Smartly detect whether the menu events should be `click`/`touch` vs `mouseover` based on what device it's running on (touch device/desktop/etc) [#22]
- [x] We need a new `offcanvas` section where particles can be dragged in and need to work like Non-visible sections (except that particles are allowed and atoms aren't). This is also going to decouple the Menu and the sidebar from being the same entity. The menu will be always end up in the offcanvas section [#31]
- [x] Consider making simpler menu layouts for secondary menus (vertical, horizontal list) [#49]

**Comment by JoomFX** [comment]
Hey @w00fz , since Beta 3 would be mostly dedicated to the Menu, can you please have a look at https://github.com/gantry/gantry5/issues/49 and maybe include it in Beta 3?

I don't really know what you have to "include in Beta 3", since we have not discussed it at all. Would you please let me know what you think about it (https://github.com/gantry/gantry5/issues/49)? 

@kevlardev I saw that you are assigned to the issue in question :) What do you think about it? Are you going to change it or you will leave it as it is ?

**Comment by w00fz** [comment]
Adding a `docs` label on this one @FrugalGeek. We are still working on it but once done there will be some changes and additions that will have to be translated into the docs. Just adding it as a memo in here.

**Comment by w00fz** [comment]
We have completed all the tasks in here! It's been very intense team work with @kevlardev and @mahagr  and myself.

We know there might still be some issues but functionality wise we have everything in place.
